### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by sellicott** [sellicott/tcc-riscv32#5]
## General Issues 
- [ ] Make tcc tests pass
 - [ ] Bootstrap tcc build
 - [ ] Generate PIE Code
   - [ ] PCREL code generation
   - [ ] GOT code generation

 ## Cross Compiler
 - [ ] Allow linker to put functions into specific locations
 - [ ] Compile MDK esp32 samples

**Comment by CorruptedVor** [comment]
And once it works, implementing the C extension?

**Comment by CorruptedVor** [comment]
tinycc mob riscv64-asm.c has the M, C, Zicsr, Zifencei stuff now
